.\" vim: tw=72 fdm=marker cms=.\\"\ %s
.
.\" FRONT MATTER {{{
.Dd Feb 04, 2016
.Os
.Dt REPOSE-ISSUE-RM 1
.
.Sh NAME
.Nm repose-issue-rm
.Nd Remove issue-specific repositories
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h | \-help
.Nm
.Op Fl n | \-print
.Ar HOST Ns ...
.Oo
.Li --
.Ar ISSUE Ns ...
.Oc
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
removes package repositories for specified maintenance updates.
.\" }}}
.
.\" OPTIONS {{{
.Sh OPTIONS
.
.Bl -tag -width "xx"
. It Fl h
Display usage instructions.
. It Fl \-help
Display this manual page.
. It Fl n Ns , Fl \-print
Write destructive operations to standard output,
do not actually perform them.
.El
.\" }}}
.
.\" OPERANDS {{{
.Sh OPERANDS
.
.Bl -tag -width "xx"
. It Ar HOST
Machine to operate on.
. It Ar ISSUE
A string of the following format:
. Bd -literal -offset "xx"
. Oo Li SUSE:Maintenance: Oc Ns Sy ISNO Ns Op Li : Ns Sy MRNO
. Ed
.El
.\" }}}
.
.\" EXAMPLES {{{
.Sh EXAMPLES
.Bd -literal
$ repose issue-rm root@{fubar,snafu}.example.org -- SUSE:Maintenance:1234 2345
.Ed
.\" }}}
.
.\" SEE ALSO {{{
.Sh SEE ALSO
.Xr repoq 1 ,
.Xr repose 1 ,
.Xr repose-issue-add 1 ,
.Xr smrt 1 ,
.Xr ssh 1 ,
.Xr sumaxy 1 ,
.Xr zypper 8 .
.\" }}}
.
.\" REPOSE {{{
.Sh REPOSE
.Nm
is part of
.Xr repose 1 .
.\" }}}
