.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH repose-help 1  "help " 
.SH NAME
repose\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBrepose help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
repose\-help\-add(1)
.TP
repose\-help\-remove(1)
.TP
repose\-help\-reset(1)
.TP
repose\-help\-install(1)
.TP
repose\-help\-clear(1)
.TP
repose\-help\-uninstall(1)
.TP
repose\-help\-list\-products(1)
.TP
repose\-help\-list\-repos(1)
.TP
repose\-help\-known\-products(1)
.TP
repose\-help\-help(1)
Print this message or the help of the given subcommand(s)
