.TH "REPOSE" "1" "2024-01-01" "1.11.2" "repose Manual"
.SH NAME
repose \- Repository manipulation tool for QAM
.SH SYNOPSIS
.B repose
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Repository manipulation tool for QAM
.SH COMMANDS
.PP
\fBadd\fP
  add specified repository to target
  See \fBrepose-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBremove\fP
  remove repository from target
  See \fBrepose-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBreset\fP
  reset target repositories to only...
  See \fBrepose-reset(1)\fP for full documentation on the \fBreset\fP command.
.PP
\fBinstall\fP
  add specified repository to target and...
  See \fBrepose-install(1)\fP for full documentation on the \fBinstall\fP command.
.PP
\fBclear\fP
  clear all repositories from target
  See \fBrepose-clear(1)\fP for full documentation on the \fBclear\fP command.
.PP
\fBuninstall\fP
  remove specified repository from target...
  See \fBrepose-uninstall(1)\fP for full documentation on the \fBuninstall\fP command.
.PP
\fBlist-products\fP
  list products on target
  See \fBrepose-list-products(1)\fP for full documentation on the \fBlist-products\fP command.
.PP
\fBlist-repos\fP
  list repositories on target
  See \fBrepose-list-repos(1)\fP for full documentation on the \fBlist-repos\fP command.
.PP
\fBknown-products\fP
  list known products by 'repose'
  See \fBrepose-known-products(1)\fP for full documentation on the \fBknown-products\fP command.
